# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: tests DB
        run: echo $DATABASE_URL!
        env:
            DATABASE_URL: ${{secrets.DATABASE_URL}}
      - name: Test with pytest
        run: |
          python -m pytest --cov-config=.coveragerc --cov --cov-report=html

#      - uses: akhileshns/heroku-deploy@v3.6.8  # This is the action
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: zebrate
#          heroku_email: kosarevsky.d@ya.ru
